### ISSUE TITLE
Interpreter Refactor on New Typed AST

### ISSUE THREAD

**Issue by stp59** [cornell-netlab/petr4#100]
Hopefully this will help fix some of the hacky features of the interpreter target architecture, including:

- eval_pipeline takes functions from interpreter as args
- duplicate code for bitstrings in target/eval - explore bitstring.ml wrapper module for bigint
- assign gets passed around a lot; explore moving lvalue ops into helper module
- passing widths along with types to the externs as type args

**Comment by hackedy** [comment]
I think #14 is the issue for this

**Comment by stp59** [comment]
oh i thought of #14 as the issue for designing the typed ast
