### ISSUE TITLE
Emit for header unions

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#116]
It looks like emit(hdr_union) is unimplemented right now. I would interpret the spec to mean it's equivalent to emit(hdr_union.field1); ...; emit(hdr_union.fieldN).

**Comment by stp59** [comment]
The code I have in front of me seems to have union emission implemented. Is this still a thing/what test is failing on this?

**Comment by hackedy** [comment]
Yeah I have no idea what this was about and nothing in the triage file links to it. Closing.
