### ISSUE TITLE
Assignments creating fresh binding in current scope instead of updating existing bindings

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#118]
Found by @axu2017 and causing test failures for the stf tests
* switch.stf
* table2.stf
* table3.p4

The fix for this is to introduce a function `update` in `env.ml` that handles an update `x =  e` by finding the current binding of `x` and changing it. Right now everything goes through `insert`, which always creates a new binding.
```
let insert_bare name value env =
  begin match env with
  | [] -> no_scopes ()
  | h :: t -> ((name, value) :: h) :: t
  end
```

**Comment by jnfoster** [comment]
Awesome detective work @axu2017!

**Comment by hackedy** [comment]
I tried just changing the definition of `insert_bare` but that didn't work. There are places where you want the old behavior (inserting bindings for function arguments) and places where you want the new behavior (assignment), and right now I think it all goes through the same code.
