### ISSUE TITLE
Pass type information from typechecker to the interpreter

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#14]
Right now (in the `old-interpreter` branch) the evaluator doesn't use any information from the typechecker and only deals with "surface types" (Types.Type.t instead of Typed.Type.t). We should figure out how to pass type information from the typechecker on to the evaluator so that we don't have to look up types twice. I think this will also involve taking a look at the handling of LValues--there should be a way to identify things as LValues in the typechecker and pass an AST to the interpreter that only has LValues on the left side of assignments.

**Comment by stp59** [comment]
We would have to move the lvalue type to Types.ml and decorate it with info.t values. Also all the functions I have for manipulating lvalues between values, expressions, and types would need to be relocated. Are you also thinking of having the type checker decorate the AST with types?

**Comment by hackedy** [comment]
I want to put it in Typed.ml, I think. I think we'll want to decorate the AST too. There might be a way to just decorate parts of the AST and do local typechecking to fill in the rest.

**Comment by stp59** [comment]
Ok... so what do we need to do to make this stuff happen?

**Comment by hackedy** [comment]
Yeah, and I can do that redesign before our next meeting. I just wanted to open an issue so that I don't forget to come up with a solution and go over the design with you, since it's going to involve changes to the interpreter.
