### ISSUE TITLE
Parameter and instantiation restrictions (spec appendix F)

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#141]
https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-calling-restrictions

Failing tests:
- examples/checker_tests/bad/issue818.p4
- examples/checker_tests/bad/issue816-1.p4
- examples/checker_tests/bad/issue1331.p4
- examples/checker_tests/bad/issue807.p4
- examples/checker_tests/bad/issue388.p4
- examples/checker_tests/bad/parser-arg.p4
- examples/checker_tests/bad/param.p4
- examples/checker_tests/bad/issue816.p4

**Comment by rudynicolop** [comment]
Tests:
- examples/checker_tests/bad/issue818.p4
- examples/checker_tests/bad/issue816-1.p4
- examples/checker_tests/bad/issue1331.p4
pass now by checking constructor param types.

**Comment by hackedy** [comment]
Fixed the rest of this in f78eaf3

**Comment by hackedy** [comment]
There are actually still two tests failing because of this.
```examples/checker_tests/bad/issue1672-bmv2.p4
examples/checker_tests/bad/string-e.p4```
