### ISSUE TITLE
Missing table typing constraints

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#144]
Tables must always have an `actions` property, and `default_action` and `entries` action_refs should have compile time known args that match the arguments (if any) given in the `actions` property.

Tests:
- examples/checker_tests/bad/missing_actions.p4
- examples/checker_tests/bad/issue473.p4
- examples/checker_tests/bad/action-bind.p4
- examples/checker_tests/bad/default_action1.p4

**Comment by rudynicolop** [comment]
Do tables need an `actions` property? In [the spec's table section](file:///Users/rudypeterson/Desktop/CS-4999/p4-spec/p4-16/spec/build/P4-16-spec.html#sec-tables),  it mentions both that:

> The standard table properties include:
> - key: An expression that describes how the key used for look-up is computed.
> - actions: A list of all actions that may be found in the table.

which seems to mean `actions` are required. But then it mentions that:

> The compiler may set the `default_action` to `NoAction` (and also insert it into the list of actions) for tables that do not define the `default_action` property.

So if a table doesn't define a default action then would the type-checker give the table the default action of `NoAction`, and then wouldn't the `table` have at least one action defined?

**Comment by rudynicolop** [comment]
Tests:
- examples/checker_tests/bad/issue473.p4
- examples/checker_tests/bad/action-bind.p4
now pass.

Still working on:
- examples/checker_tests/bad/missing_actions.p4
- examples/checker_tests/bad/default_action1.p4

**Comment by rudynicolop** [comment]
Why should this p4 program typecheck,
`examples/checker_tests/good/issue2037.p4`
```p4
action a() {}
control c() {
    table t {
        actions = { .a; }
        default_action = a;
    }
    apply {}
}
```
whereas this p4 program shouldn't typecheck?
`examples/checker_tests/bad/default_action1.p4`
```p4
action b() {}

control c() {
    action a() {}
    action b() {}
    table t {
        actions = { a; b; }
        default_action = .b();  // not the same b
    }
    apply {}
}
```

Shouldn't both programs fail to typecheck because the default action has a different name than the one in the action's property? In `good/issues2037` the default action is set to the non-toplevel name where only the top-level name exists, and in `bad/default_action1` it is set to the top-level name instead of the local name in the `actions` property.

**Comment by jnfoster** [comment]
In the second program, the `b` in the `actions` block refers to the one defined in `c`. However, the `default_action`, namely `.b` refers to the one at the top level. Hence, the `default_action` is not an element of the `actions` which is an error.

**Comment by hackedy** [comment]
All fixed
