### ISSUE TITLE
Type argument inference

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#16]
The typechecker does not infer type arguments in instantiations or in calls to extern methods.

**Comment by hackedy** [comment]
0200457 completes an implementation of type inference for instantiations and function calls of the form `f(args)`.

We still need to deal with wildcard type arguments like `f<_, _, _>(args)`.

The inference code can't handle [nested_call.p4](https://github.com/cornell-netlab/petr4/blob/complete-checker/examples/inference/nested_call.p4). I thought this was about wildcard arguments, but removing the wildcard arguments still results in an error.
```
  ("could not solve type equality t1 = t2" (t1 (TypeName C))
   (t2 (TypeName A)))
```
I think this is happening because the current implementation refuses to infer type variables as type arguments, even if they're in scope and not in the set of unknown variables being solved for.

**Comment by jnfoster** [comment]
Amazing!

**Comment by hackedy** [comment]
Closing this because type inference is implemented and there are other open issues for the remaining bugs in the implementation.
