### ISSUE TITLE
V1 Traffic Management

### ISSUE THREAD

**Issue by stp59** [cornell-netlab/petr4#166]
Need to understand and implement the blackboxes in the V1 pipeline, especially how egress spec affects the egress port.

**Comment by jnfoster** [comment]
In a nutshell, ignoring things like cloning, resubmission, etc. `egress_spec` is copied to `egress_port` between `IngressDeparser` and `EgressParser` unless it is `DROP_PORT`

https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L607

**Comment by stp59** [comment]
I was just looking at this. Perhaps one of our contributions eventually could be a better specification/semantics of these targets? Also Alex and I were wondering how stf checks for dropped packets. What will the egress port be if the packet is dropped?
