### ISSUE TITLE
Extracting on non-byte boundaries causes infinite loop

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#174]
I'm noticing that `packet_of_bytes` spins out if asked to extract a `VBit` of width 7. The Cstruct API only allows byte-aligned operations on the buffer so this may be a pain to fix.

**Comment by jnfoster** [comment]
This is fine. Let's say that we only support byte-aligned headers.

-N

**Comment by hackedy** [comment]
:+1: Just added a precondition check in my branch so it crashes instead of spinning out.

**Comment by hackedy** [comment]
Noticed that p4c will reject a header if the width of the entire header is not byte aligned, but it doesn't care about fields. See [this test](https://github.com/cornell-netlab/petr4/blob/7339af519ce41b249145c13a70807223b0766598/examples/checker_tests/bad/header-not-multiple-of-bytes-bmv2.p4).

**Comment by hackedy** [comment]
OK, let's try to get rid of the field alignment requirement

**Comment by stp59** [comment]
Assuming that "extraction" is a typo and the intent was "emission", i think i came up with a fix where i concatenate all of the fields of a header into a single bitstring before converting them to a Cstruct. I couldn't find the test linked above but this change did cause about 5 tests to pass without introducing any regressions. Should this be enough to mark this issue resolved?
