### ISSUE TITLE
Missing support for serializable enums

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#176]
Causing a failure for `examples/checker_tests/good/table-entries-ser-enum-bmv2.p4` but I think it might be another face of the implicit casts issue #155.

**Comment by stp59** [comment]
I just came across this in my debugging of the interpreter; seems like a pretty simple fix for someone familiar with the type checker?

**Comment by hackedy** [comment]
Looks like this has been fixed, the test passes on master (cd2faffa439d0f196f10f0ba28573d3d6a98ec3f).
