### ISSUE TITLE
questions and issues

### ISSUE THREAD

**Issue by jnfoster** [cornell-netlab/petr4#197]
* Why does the expression typing judgment generate a direction as output?
* What's an example of an expression whose type generates a non-none direction as output?
* We need to substitute Xs for rhos in the return type for Function-Call
* Madoko has two subsections named `#sec-function-calls` (and probably others) so the HTML links don't work. We should add a consistent label to disambiguate these -- e.g., `#sec-type-function-calls`.
* Why are we giving inference rules for every built-in function in 4.4.9? It seems like we should instead populate a built-in environment with these.

**Comment by rudynicolop** [comment]
>Madoko has two subsections named #sec-function-calls (and probably others) so the HTML links don't work. We should add a consistent label to disambiguate these -- e.g., #sec-type-function-calls.

I made section names unique (I think) so the table of contents links should have no conflicts.
