### ISSUE TITLE
Instructions for installing petr4 starting from fresh Ubuntu Linux installation?

### ISSUE THREAD

**Issue by jafingerhut** [cornell-netlab/petr4#2]
I have been trying unsuccessfully today to install petr4 on an unmodified freshly installed Ubuntu 16.04 or Ubuntu 18.04 Desktop Linux VM.

What OS and version do you use?

When I attempted to run `opam init` to install OPAM 2.0.4 on Ubuntu 16.04, I got an error that I needed to install bubblewrap (also called bwrap, I think).  There is no Ubuntu 16.04 package with either of those names, and I didn't want to go down the path of installing that from source if there is an easier way to get there.

When I attempted to follow the install steps from a freshly installed Ubuntu 18.04 VM, I was able to successfully install OPAM 2.0.4, and `opam init` installed version 4.07.1 of the OCaml compiler.  This is slightly later than the minimum version 4.06.0 mentioned in petr4's README, so I hope that works, too.  So far, so good.

Then I attempted to run the command `opam pin add petr4 .` from my $HOME directory, but there was some kind of error message about a conflict or overlap between directories $HOME and $HOME/.opam/<something>   (I can get the exact error message for you if it helps diagnose this).  So I created a directory `$HOME/install`, `cd install`, and ran `opam pin add petr4 .` inside of that directory.  Lots of OCaml software appeared to be compiled, but eventually there was another error message that I do not know how to diagnose.  The error message is highlighted by the few lines this link links to: https://github.com/jafingerhut/p4-guide/blob/master/bin/output-install-petr4/ubuntu18.04-log.txt#L536-L550

but that entire file shows all commands run on the system in my attempt to install petr4, starting from a freshly installed Ubuntu 18.04 Desktop Linux system with all updates from Canonical as of 2019-May-11.

**Comment by jafingerhut** [comment]
Here is the error message I see when trying the command `opam pin add petr4 .` from my $HOME directory `/home/jafinger`, in case it helps to know, but I suspect this is probably a well known thing for anyone experienced in using `opam`:
```
[ERROR] Cannot sync /home/jafinger/ into
        /home/jafinger/.opam/4.06.0/.opam-switch/sources/petr4: they overlap
[ERROR] Error getting source from file:///home/jafinger:
          - /home/jafinger
```

**Comment by jafingerhut** [comment]
I also tried doing `opam switch 4.06.0` to the OCaml compiler version explicitly mentioned in the petr4 README, but got the same failing result as described in an earlier comment, so it does not seem that 4.06.0 vs. 4.07.1 makes a difference here.

**Comment by jafingerhut** [comment]
[Me with egg on face]   OK, I just realized that I had not made a clone of this repository on the machine where I was trying the install, and after doing that and running the `opam pin add petr4 .` command from within the root directory of that clone, things went better on Ubuntu 18.04.  Sigh.

If you want to indulge others who would otherwise make a similar mistake in the future, adding `git clone https://github.com/cornell-netlab/petr4` and `cd petr4` just before the `opam pin add petr4 .` command in the README would probably do the trick.

I am still a little curious to know which OS and version you use for development work.  If Ubuntu 16.04, do you have a recommendation for installing bubblewrap, or avoiding the need to do so?

**Comment by jafingerhut** [comment]
I have created a bash script that can install petr4 on an Ubuntu 18.04 desktop Linux machine, freshly installed, here: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-petr4.sh

You are welcome to copy it into this repo, link to it, etc. if you wish.

**Comment by hackedy** [comment]
Hi Andy, sorry you had to jump through all these hoops to install Petr4. I'm not sure where to get `bubblewrap` on older Ubuntu versions, I wrote the README by trying to install Petr4 in a fresh Ubuntu Desktop 18.04 VM.

As for the difficulty with `opam pin` and checking out the repo, I think we have a copy of petr4 in the official OPAM repository now and don't have to deal with that. I'll update the README to just say `opam install petr4` and move the pin instructions to a "building from Git" section, or something like that.
