### ISSUE TITLE
Zero as dividend failing typechecker

### ISSUE THREAD

**Issue by axu2017** [cornell-netlab/petr4#207]
test failing: issue2287-bmv2.stf

**Comment by stp59** [comment]
i saw this earlier. its not dividing by zero its dividing zero. a strict interpretation of the type-checker would show that this program is invalid, but it seems like p4c accepts it anyway. this might be a bug in their type-checker.

**Comment by hackedy** [comment]
The program is valid and should typecheck. The spec says division must have positive arguments but that seems like a bug in the spec. They probably mean that the divisor is (strictly) positive and the dividend is just nonnegative
