### ISSUE TITLE
`int` type can't be parsed

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#22]
There's a program [fcallNoInfer.p4](https://github.com/cornell-netlab/petr4/blob/complete-checker/examples/inference/fcallNoInfer.p4) in `examples/inference` with a function
```
int f(in int y){
    return y;
}
```
which we can't parse, because we don't let P4 programmers refer to the infinite-precision integer type `int` in source programs. This is either a bug in the example program or in our parser.

**Comment by jnfoster** [comment]
Seems like a parser bug.
