### ISSUE TITLE
Type Soundness Proof is Exploding...

### ISSUE THREAD

**Issue by rudynicolop** [cornell-netlab/petr4#223]
### The following are unresolved:
- There needs to be a **typing-judgment for values**, and for cases like function calls it would be nice if it was ***context-independent***
- ~~The same name `sig` is used to refer to both type-checking signals (unit,void) for statements and evaluation signals (continue, return, exit, reject). They need to be distinct.~~
- **There are many helper lemmas and corollaries**. Even though proofs for some of them are straight-forward, some seem tricky, and others would perform induction on the derivation of expression or statement evaluation, i.e. many cases.
- I have done many of the cases for expressions and statements, however there is still a lot of work to be done, and in places where I felt my logic was sketchy I marked "TODO" or "sketchy'.
- For declarations such as controls and parsers the typing context G is extended with the name of the declaration X and a constructor but in the dynamic semantics no new value is bound to name X via environment E. If X was previously bound to a value of a different type then preservation will not hold. I am not sure how to guarantee this edge-case will not occur...

If we can  ***identify and isolate*** p4's **core language** then perhaps the proof could be restricted to that subset of p4. Otherwise there is ***an explosion*** of cases.

**Comment by hackedy** [comment]
I'm tied up with default arguments for the evening but I can help out with this as soon as I'm done. I think we can find a way to simplify things if we go back to the semantics and make values a subset of expressions and fix the ambiguity of `sig`, among other things.

**Comment by rudynicolop** [comment]
>The same name `sig` is used to refer to both type-checking signals (unit,void) for statements and evaluation signals (continue, return, exit, reject). They need to be distinct.

I just changed the statement type-checking signal `sig` to result `R`.

**Comment by rudynicolop** [comment]
New dilemma: for declarations such as controls and parsers the typing context `G` is extended with the name of the declaration `X` and a constructor but in the dynamic semantics no new value is bound to name `X` via environment `E`.
If `X` was previously bound to a value of a different type then preservation will not hold. I am not sure how to guarantee this edge-case will not occur...

**Comment by jnfoster** [comment]
I believe `p4c` forbids duplicate declarations of parsers and controls. We could adopt that restriction to make this go through and then propose it for addition to the specification.

(Otherwise, I think we need closures for them too, and that feels weird given how these are used.)

**Comment by rudynicolop** [comment]
I don't understand the following behaviour.

I created an example (`examples/checker_tests/good/decl-soundness.p4`) where a `const` is declared with the same name as a following `control`. 

Both the type-checker and interpreter were ok with the following:

```p4
// modified enum-bmv2.p4

#include <core.p4>
#include <v1model.p4>

header hdr {
    bit<32> a;
    bit<32> b;
    bit<32> c;
}

enum Choice {
    First,
    Second
}

const bit<32> compute = 0;

control compute(inout hdr h)
{
    apply {
        // Test enum lowering
        Choice c = Choice.First;

        if (c == Choice.Second)
            h.c = h.a;
        else
            h.c = h.b;
    }
}

#include "arith-inline-skeleton.p4"
```
but the parser did not accept:
```p4
// modified enum-bmv2.p4

#include <core.p4>
#include <v1model.p4>

header hdr {
    bit<32> a;
    bit<32> b;
    bit<32> c;
}

enum Choice {
    First,
    Second
}

const bit<32> compute = 0;

control compute(inout hdr h)
{
    apply {
        // Test enum lowering
        Choice c = Choice.First;

        if (c == Choice.Second)
            h.c = (h.a + compute); // plus 0
        else
            h.c = (h.b + compute); // plus 0
    }
}

#include "arith-inline-skeleton.p4"
```
When I tried to type-check the above I got a syntax error on the line `h.c = (h.a + compute);`. I thought I would get a typing error but it didn't even get that far. 

I am not sure what the expected behavior of these programs is...

**Comment by hackedy** [comment]
You get a syntax error because the "lexer hack" turns compute into a type name, which isn't grammatically allowed in expressions.

**Comment by hackedy** [comment]
I'm working on fixing #135 in the implementation, which should address this...

**Comment by rudynicolop** [comment]
>There needs to be a typing-judgment for values, and for cases like function calls it would be nice if it was context-independent.
I just pushed some rules for typing values. Keeping it typing-context-free seemed tricky for the following:
- Functions, Parsers, Controls, and Tables, where to check the innards maybe we need some outer context, or perhaps it can generate a sufficient context from the parameters.
- Header Stacks and Unions, whose fields need to be restricted to headers (which the implementation checks but rules currently do not).
- Enums, `name1`.name2`, need to check that there exists a enum `name1` with field `name2` and I am not sure how to do this without a context...

**Comment by hackedy** [comment]
What about typechecking values under a type environment but without a variable environment (gamma)?

**Comment by hackedy** [comment]
Also, don't worry about enums. We can ignore enums

**Comment by rudynicolop** [comment]
>What about typechecking values under a type environment but without a variable environment (gamma)?
Maybe...type-checking values with a context became tricky in places like function calls, where the value types under the context of the function declaration but I need to show it also types under the call context. But maybe this is not so bad with just Delta...
