### ISSUE TITLE
STF missing parameters for action in issue870_ebpf.p4

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#230]
The P4 file has an action `pipe.Reject(IPv4Address add)` that updates the source IP of the packet before flagging it to be dropped. The STF file uses the action but doesn't pass any parameters to it, so the interpreter ends up crashing.
```
add pipe.Check_src_ip 0 key.field0:0x0a019846 pipe.Reject()
```
We should double check what the p4c/bmv2 does with this test... maybe I am misunderstanding the meaning of the STF here.

**Comment by stp59** [comment]
I add an arg here and it passes. My guess is that p4c's stf semantics has stf implicitly adding in the args or something
