### ISSUE TITLE
Evaluating lvalues and values independently in copy-in copy-out

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#235]
It looks like the current implementation evaluates things twice, once to get the value for `in` and once to get the lvalue for `out`. Here's a condensed example... the apply block of C should increment hdr.h[1], but instead it increments hdr.h[2].
```
header h_t {
    bit<32> v;
}
struct metadata { }
struct headers {
    h_t[10] h;
}
bit<32> incrAndReturn(inout bit<32> x) {
    x = x + 1;
    return x;
}
void incrHdr(inout h_t x) {
    x.v = x.v + 1;
}
control C(headers hdr) {
    apply {
        bit<32> x = 0;
        incrHdr(hdr.h[incrAndReturn(x)]);
    }
}
```

**Comment by stp59** [comment]
hmm I noticed this but thought it wouldn't affect correctness. Will investigate further.
