### ISSUE TITLE
Line number error reporting broken

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#59]
I think this is due to lexer changes made in #58 but I don't know the internals of the lexer well enough to fix it. Example:
```
% petr4 parse examples/checker_tests/good/extern3.p4 
File examples/checker_tests/good/extern3.p4", line 17, characters 127-131: (Petr4.Parser.MenhirBasics.Error)
```

Extern3.p4 does not have any lines that are 127 characters long, and I'm pretty sure the actual problem triggering this error is happening on line 24...

**Comment by jnfoster** [comment]
Fixed by #60 and #61.
