### ISSUE TITLE
Ranges between arbitrary width integer constants

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#82]
We reject ranges like `1..10` between two arbitrary width integers. This is [what the spec seems to say](https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-ranges), but there are tests in the test suite that do it anyway (e.g., examples/checker_tests/good/table-entries-range-bmv2.p4).

**Comment by hackedy** [comment]
Filed a spec bug p4lang/p4-spec#842 for this.

**Comment by jnfoster** [comment]
Unless I missed it, the range issue was not mentioned in p4lang-p4-spec#842

**Comment by hackedy** [comment]
Oops, mixed it up with masks &&& since they're basically the same problem. I added a comment over there.
