### ISSUE TITLE
When are two enum types the same type?

### ISSUE THREAD

**Issue by hackedy** [cornell-netlab/petr4#9]
If two enums have the same members and no underlying type are they equal? What about if they have underlying types and those types are the same?

**Comment by jnfoster** [comment]
It seems enums are treated nominally...

**Comment by hackedy** [comment]
Returning to this... we're treating them structurally right now, should fix that.

**Comment by hackedy** [comment]
Fixed in f61eacbea7b0aa8537b8109cab08fee07d64cf76
